version: '2'
services:
  excella-retro:
    container_name: excella-retro-ui
    image: excella-retro-ui-prod
    build:
      context: .
      dockerfile: Dockerfile.Prod
    ports:
      - 80:80
    volumes:
      - .:/home/app/excella-retro
      - /home/app/excella-retro/node_modules