version: '2'
services:
  excella-retro:
    container_name: excella-retro
    build: .
    command: "npm start --host 0.0.0.0"
    ports:
      - 4200:4200
    volumes:
      - .:/home/app/excella-retro
      - /home/app/excella-retro/node_modules